#include "main.hpp"

tWoundDef WoundsTable[] = {
    {WOUND_TYPE_UNKNOWN, WOUND_LEVEL_NONE, (WOUND_MOD_BASE*WOUND_LEVEL_NONE), },
    {WOUND_TYPE_UNKNOWN, WOUND_LEVEL_GRAZE, (WOUND_MOD_BASE*WOUND_LEVEL_GRAZE), },
    {WOUND_TYPE_UNKNOWN, WOUND_LEVEL_SEVERE, (WOUND_MOD_BASE*WOUND_LEVEL_SEVERE), },
    {WOUND_TYPE_UNKNOWN, WOUND_LEVEL_GRIEVOUS, (WOUND_MOD_BASE*WOUND_LEVEL_GRIEVOUS), },
    {WOUND_TYPE_UNKNOWN, WOUND_LEVEL_KILLING, (WOUND_MOD_BASE*WOUND_LEVEL_KILLING), },
    {WOUND_TYPE_UNKNOWN, WOUND_LEVEL_UNKNOWN, (0), (0)}
};
